app/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_user, logout_user, login_required
from ..models import Usuario
import sqlalchemy as sa
from ..forms.auth import LoginForm, RegistrationForm
from app import db

auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.agendamentos'))
    form = LoginForm()
    if form.validate_on_submit():
        usuario = Usuario.query.filter_by(email = form.email.data).first()
        if usuario is None and not usuario.checar_senha(form.senha.data):
            flash('E-mail ou senha inválido.')
            return redirect(url_for('auth.login'))
        login_user(usuario)
        return redirect(url_for('index_bp.index'))
    return render_template('auth/login.html', title = 'Log In', form = form)

@auth.route('/cadastro')
def cadastro():
    if current_user.is_authenticated:
        return redirect(url_for('auth.login'))
    form = RegistrationForm()
    if form.validate_on_submit():
        usuario =  Usuario(nome = form.nome.data, cpf = form.cpf.data, data_nascimento = form.data_nascimento.data, email = form.email.data, senha = form.senha.data)
        usuario.criar_senha(form.senha.data)
        db.session.commit(usuario)
        db.session.add()
        flash('Parabéns, você é um usuário cadastrado!')
        redirect(url_for('auth.login'))
    return render_template('auth/cadastro.html', title = 'Cadastro', form = form)

@auth.route('/esqueci-senha', methods=['GET', 'POST'])
@login_required
def esqueciSenha():
    if request.method == 'POST':
        email = request.form.get('email', '').strip()
        if not email:
            flash('Por favor, informe um e-mail válido.', 'error')
            return render_template('auth/esqueci-senha.html', title='Esqueci a Senha')

        # Aqui você integraria com o serviço de e-mail para enviar o link de recuperação.
        # Exemplo: send_reset_email(email)
        flash('Se o e-mail estiver cadastrado, enviamos um link de recuperação.', 'success')
        return redirect(url_for('login'))

    return render_template('auth/esqueci-senha.html', title='Esqueci a Senha')

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index_bp.index'))

@auth.user_loader
def load_user(user_id):
    return Usuario.query.filter(Usuario.id == int(user_id)).first()

app/routes/index_bp.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from app import db

index_bp = Blueprint('index_bp', __name__)

@index_bp.route('/')
@index_bp.route('/index')
def index():
    return render_template('index.html', title = 'Bem-vindo ao ITZN!')

@index_bp.route('/eventos')
def eventos():
    return render_template('main/eventos.html', title = 'Eventos')

@index_bp.route('/editais')
def editais():
    return render_template('main/editais.html', title = 'Editais')

@index_bp.route('/sobre')
def sobre():
    return render_template('main/sobre.html', title = 'Sobre Nós')

@index_bp.route('/contato')
def contato():
    return render_template('main/contato.html', title = 'Contato')

app/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/css/global.css">
    <link rel="stylesheet" href="../static/css/base.css">
    <title>Document</title>
</head>

<body>

    <header>
        <section class="flex alinhar-extremidades meio-vertical">
            <div class="flex meio-vertical">
                <button><img src="../../static/imgs/base/menu.svg" alt="menu" class="menu-icon"></button>
                <img src="../../static/imgs/base/itzn brand.svg" alt="Logo ITZN">
            </div>
            <div class="perfil flex">
                 <img src="../../static/imgs/base/default-user.png" alt="perfil de usuario">
            </div>
        </section>
    </header>
       

    {% block content %}{% endblock %}
</body>

</html>

app/templates/base2.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/css/global.css">
    <link rel="stylesheet" href="../static/css/base2.css">
    <title>Document</title>
</head>

<body>

    <header class="flex centralizar alinhar-extremidades">
        <section class="container">
            <nav class="flex alinhar-extremidades">
                <div class="flex">
                    <a href="{{ url_for('index_bp.index') }}"><img src="../static/imgs/base/itzn brand.svg" alt=""></a>
                    <ul class="flex centralizar">
                        <li><a href="{{ url_for('index_bp.index') }}" class="nav-link {% if request.endpoint and 'index' in request.endpoint %}active{% endif %}">Home</a></li>
                        <li><a href="{{ url_for('index_bp.eventos') }}" class="nav-link {% if request.endpoint and 'eventos' in request.endpoint %}active{% endif %}">Eventos</a></li>
                        <li><a href="{{ url_for('index_bp.editais') }}" class="nav-link {% if request.endpoint and 'editais' in request.endpoint %}active{% endif %}">Editais</a></li>
                        <li><a href="{{ url_for('index_bp.sobre') }}" class="nav-link {% if request.endpoint and 'sobre' in request.endpoint %}active{% endif %}">Sobre</a></li>
                        <li><a href="{{ url_for('index_bp.contato') }}" class="nav-link {% if request.endpoint and 'contato' in request.endpoint %}active{% endif %}">Contato</a></li>
                    </ul>
                </div>
                <div class="flex centralizar">
                    <a class="flex centralizar" href="{{ url_for('auth.login') }}">
                        Login
                    </a>
                    <a class="flex centralizar" href="{{ url_for('auth.cadastro') }}">
                        Cadastro
                    </a>
                </div>
            </nav>
        </section>
    </header>

    {% block content %}{% endblock %}

    <footer class="flex coluna centralizar">
        <div class="container">
            <div class="cont-footer flex alinhar-extremidades meio-vertical">
                <div class="flex coluna">
                    <a href="{{ url_for('index_bp.index') }}"><img src="../static/imgs/base/itzn brand white.svg" alt=""></a>
                    <h3>Incubadora do Campus Natal Zona Norte</h3>
                </div>
                <div class="flex esquerda">
                    <ul class="flex coluna">
                        <li><a href="{{ url_for('index_bp.index') }}" class="nav-link {% if request.endpoint and 'index' in request.endpoint %}active{% endif %}">Home</a></li>
                        <li><a href="{{ url_for('index_bp.editais') }}" class="nav-link {% if request.endpoint and 'editais' in request.endpoint %}active{% endif %}">Editais</a></li>
                        <li><a href="{{ url_for('index_bp.sobre') }}" class="nav-link {% if request.endpoint and 'sobre' in request.endpoint %}active{% endif %}">Sobre</a></li>
                        <li><a href="{{ url_for('index_bp.contato') }}" class="nav-link {% if request.endpoint and 'contato' in request.endpoint %}active{% endif %}">Contato</a></li>
                    </ul>
                </div>
                <div class="flex coluna">
                    <h3>Contato</h3>
                    <div class="flex coluna">
                        <div class="flex meio-vertical">
                            <img src="../static/imgs/base/WhatsApp.svg" alt="">
                            <a href=""><span>+55 84 4006-9538</span></a>
                        </div>
                        <div class="flex meio-vertical">
                            <img src="../static/imgs/base/location-pin_svgrepo.com.svg" alt="">
                            <a href="https://www.google.com/maps/place/IFRN+Campus+Natal-Zona+Norte/@-5.7490661,-35.2604531,20z/data=!4m15!1m8!3m7!1s0x7b3abb568325555:0x68b03628eca728c4!2sR.+Brusque,+2926+-+Potengi,+Natal+-+RN,+59112-490!3b1!8m2!3d-5.7491829!4d-35.2602231!16s%2Fg%2F11mkmpgwq1!3m5!1s0x7b3abb5048b2fcb:0xef4f6c5edaa6d542!8m2!3d-5.7490999!4d-35.2604103!16s%2Fg%2F1tctxs6z?authuser=0&entry=ttu&g_ep=EgoyMDI1MTEyMC4xIKXMDSoASAFQAw%3D%3D"><span>R. Brusque, 2926 - Potengi, Natal - RN, 59112-490</span></a>
                        </div>
                        <div class="flex meio-vertical">
                            <img src="../static/imgs/base/instagram_svgrepo.com.svg" alt="">
                            <a href="https://www.instagram.com/itznincubadora/"><span>@itznincubadora</span></a>
                        </div>
                    </div>
                </div>
                <img src="../static/imgs/base/logo ifrn.svg" alt="">
            </div>
        </div>
        <div class="copyright flex centralizar">
            <span>Copyright ©2025 ITZN. All rights reserved</span>
        </div>
    </footer>

</body>

</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/css/global.css">
    <link rel="stylesheet" href="../static/css/index.css">
    <link rel="shortcut icon" href="../../static/imgs/favicon/logo-itzn.ico" type="image/x-icon">
    <title>{{ title }}</title>
</head>

<body>

    {% extends 'base2.html' %}

    {% block content %}
    <main class="flex coluna meio-vertical">
        <div class="herobanner flex meio-horizontal">
            <section class="container flex alinhar-extremidades">
                <div class="texto-herobanner flex coluna">
                    <div class="flex coluna">
                        <h1>Incubadora Tecnológica do IFRN - Zona Norte</h1>
                        <h2>Nosso propósito é fomentar o empreendorismo inovador. Um ambiente dedicado ao
                            desenvolvimento de
                            startups e empreendimentos de base tecnológica.</h2>
                    </div>
                    <a class="flex centralizar" href="{{ url_for('index_bp.sobre') }}">
                        Saber mais
                    </a>
                    <div class="flex">
                        <img src="../static/imgs/base/logo ifrn.svg" alt="">
                        <img src="../static/imgs/index/logo-sebrae-transparente-194541244 1.png" alt="">
                    </div>
                </div>
                <div class="homem flex">
                    <img class="" src="../static/imgs/index/homem.png" alt="">
                </div>
            </section>
        </div>

        <div class="o-que-fazemos flex meio-horizontal">
            <section class="container flex alinhar-extremidades meio-vertical">
                <div class="conteudo flex">
                    <div class="flex coluna">
                        <h3>O Que Fazemos</h3>
                        <p>Nosso propósito é fomentar o empreendedorismo inovador, criando um ambiente dinâmico e
                            colaborativo voltado para o desenvolvimento de startups e empreendimentos de base
                            tecnológica.
                            Buscamos impulsionar ideias que transformem realidades, conectando pessoas, recursos e
                            conhecimento para gerar soluções criativas e sustentáveis. Acreditamos que a inovação é o
                            motor
                            do progresso, e, por isso, promovemos iniciativas que estimulem a experimentação, o
                            aprendizado
                            contínuo e a troca de experiências entre empreendedores, mentores e instituições parceiras.
                            Nosso objetivo é contribuir para o fortalecimento do ecossistema de inovação, estimulando o
                            crescimento econômico, a competitividade e o impacto positivo na sociedade.</p>
                    </div>
                    <img class="equipe-itzn" src="../static/imgs/index/WhatsApp Image 2025-10-23 at 17.39.46 3.png"
                        alt="">
                </div>
            </section>
        </div>

        <section class="container">
            <div class="espac flex coluna centralizar">
                <h3>Em que podemos ajudar</h3>
                <div class="em-que-podemos-ajudar flex">
                    <div class="card flex coluna centralizar">
                        <div class="cont flex coluna meio-vertical">
                            <img src="../static/imgs/index/gestao-negocios.svg" alt="">
                            <div class="flex coluna centralizar">
                                <b>Gestão de negócios</b>
                                <p>Estruturação e planejamento estratégico para sua startup</p>
                            </div>
                        </div>
                    </div>
                    <div class="card flex coluna centralizar">
                        <div class="cont flex coluna meio-vertical">
                            <img src="../static/imgs/index/metodos-ageis.svg" alt="">
                            <div class="flex coluna centralizar">
                                <b>Métodos Ágeis</b>
                                <p>Implementação de métodos ágeis para otimizar processos e aumentar a eficiência</p>
                            </div>
                        </div>
                    </div>
                    <div class="card flex coluna centralizar">
                        <div class="cont flex coluna meio-vertical">
                            <img src="../static/imgs/index/marketing.svg" alt="">
                            <div class="flex coluna centralizar">
                                <b>Marketing</b>
                                <p>Marketing estratégico para fortalecer sua marca e atrair resultados</p>
                            </div>
                        </div>
                    </div>
                    <div class="card flex coluna centralizar">
                        <div class="cont flex coluna meio-vertical">
                            <img src="../static/imgs/index/gestao-financeira.svg" alt="">
                            <div class="flex coluna centralizar">
                                <b>Gestão financeira</b>
                                <p>Gestão financeira e controle de recursos para o futuro da sua startup</p>
                            </div>
                        </div>
                    </div>
                    <div class="card flex coluna centralizar">
                        <div class="cont flex coluna meio-vertical">
                            <img src="../static/imgs/index/gestao-projetos.svg" alt="">
                            <div class="flex coluna centralizar">
                                <b>Gestão de projetos</b>
                                <p>Planejamento e gestão de projetos para transformar ideias em resultados</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="container flex meio-horizontal">
            <div class="etapas flex alinhar-extremidades">
                <div class="card flex coluna centralizar">
                    <div class="flex centralizar">
                        <img src="../static/imgs/index/pre-incubacao.svg" alt="">
                    </div>
                    <h3>Pré-incubação</h3>
                    <p>A pré-incubação, com duração de 3 a 9 meses, inclui capacitação, validação da ideia e elaboração do plano de negócios, com avaliações e orientações periódicas, podendo levar à continuidade, ajuste ou suspensão do projeto.</p>
                </div>
                <div class="card flex coluna centralizar">
                    <div class="flex centralizar">
                        <img src="../static/imgs/index/incubacao.svg" alt="">
                    </div>
                    <h3>Incubação</h3>
                    <p>A incubação, com duração de 12 a 24 meses, apoia o negócio já validado em sua formalização e crescimento, oferecendo capacitação, acompanhamento contínuo e acesso à estrutura da ITZN.</p>
                </div>
                <div class="card flex coluna centralizar">
                    <div class="flex centralizar">
                        <img src="../static/imgs/index/graduacao.svg" alt="">
                    </div>
                    <h3>Graduação</h3>
                    <p>A graduação ocorre quando a empresa atinge solidez financeira e consolidação no mercado, liberando o espaço físico (se residente) e iniciando um novo ciclo de acompanhamento pela ITZN. Essa fase dura de 6 meses a 2 anos, com o foco em crescimento e escalabilidade.</p>
                </div>
            </div>
        </section>

        <section class="container">
            <div class="espac-beneficios flex coluna">
                <div class="titulos flex coluna centralizar">
                    <h3>Por que escolher a ITZN?</h3>
                    <p>Benefícios exclusivos para empreendedores inovadores</p>
                </div>
                <div class="lista-beneficios flex alinhar-extremidades">
                    <div class="beneficio flex">
                        <div class="flex centralizar">
                            <img src="../static/imgs/index/inf-comp.svg" alt="">
                        </div>
                        <div class="flex coluna">
                            <h3>Infraestrutura Completa</h3>
                            <p>Escritórios, laboratórios e equipamentos de ponta à sua disposição</p>
                        </div>
                    </div>
                    <div class="beneficio flex">
                        <div class="flex centralizar">
                            <img src="../static/imgs/index/ment-espec.svg" alt="">
                        </div>
                        <div class="flex coluna">
                            <h3>Mentoria Especializada</h3>
                            <p>Acesso a mentores experientes em tecnologia e negócios</p>
                        </div>
                    </div>
                    <div class="beneficio flex">
                        <div class="flex centralizar">
                            <img src="../static/imgs/index/web.svg" alt="">
                        </div>
                        <div class="flex coluna">
                            <h3>Networking</h3>
                            <p>Conexões com investidores, empresas e outras startups</p>
                        </div>
                    </div>
                    <div class="beneficio flex">
                        <div class="flex centralizar">
                            <img src="../static/imgs/index/alvo.svg" alt="">
                        </div>
                        <div class="flex coluna">
                            <h3>Capacitação Contínua</h3>
                            <p>Workshops, treinamentos e eventos para seu desenvolvimento</p>
                        </div>
                    </div>
                    <div class="beneficio flex">
                        <div class="flex centralizar">
                            <img src="../static/imgs/index/cifrao.svg" alt="">
                        </div>
                        <div class="flex coluna">
                            <h3>Apoio Financeiro</h3>
                            <p>Auxílio na captação de recursos e acesso a editais</p>
                        </div>
                    </div>
                    <div class="beneficio flex">
                        <div class="flex centralizar">
                            <img src="../static/imgs/index/lampada.svg" alt="">
                        </div>
                        <div class="flex coluna">
                            <h3>Consultoria Jurídica</h3>
                            <p>Orientação legal para estruturação do seu negócio</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="container">
            <div class="parcerias flex centralizar coluna">
                <div class="flex coluna centralizar">
                    <h3>Projetos e Parcerias (2023 - 2025)</h3>
                    <p>A atuação da incubadora é fortalecida por uma rede sólida de parceiros:</p>
                </div>
                <div class="flex coluna centralizar">
                    <h3>Empreendimentos 2024</h3>
                    <div>
                        <img src="../static/imgs/index/Apresentação IT.ZN-09 1.png" alt="">
                    </div>
                </div>
            </div>
        </section>
    </main>
    {% endblock %}

</body>

</html>